### ISSUE TITLE
[Suggestion] Add Live Wallpaper support

### ISSUE THREAD

**Issue by Spl1Zz** [Yanndroid/DualWallpaper#22] opened 2024-07-31 20:07 UTC
I use a live Wallpaper from Magic Fluids, and it would be so epic if i could let it change automatically please consider adding live wallpaper support <3

**Comment by Yanndroid** [comment] 2024-07-31 20:49
I already tried to do that but unfortunately I can't take over Live Wallpapers from other apps.

(Duplicate of #16)

**Closed as not planned by Yanndroid** 2024-07-31 20:49 UTC
